# Default initial positions for isaac_twin's ros2_control fake system

initial_positions:
  prismatic_joint_1: 1
  prismatic_joint_2: 1
  spherical_1_x: 0
  spherical_1_y: 0
  spherical_1_z: 0
  spherical_2_x: 0
  spherical_2_y: 0
  spherical_2_z: 0