# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - group_test_controller

  group_test_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - spherical_1_x
      - spherical_1_y
      - spherical_1_z
      - prismatic_joint_1
      - spherical_2_x
      - spherical_2_y
      - spherical_2_z
      - prismatic_joint_2