# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    group_test_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

group_test_controller:
  ros__parameters:
    joints:
      - spherical_1_x
      - spherical_1_y
      - spherical_1_z
      - prismatic_joint_1
      - spherical_2_x
      - spherical_2_y
      - spherical_2_z
      - prismatic_joint_2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity